"""initial migration with updated_at, soft_delete, and indexes

Revision ID: 24e7f173a524
Revises: 
Create Date: 2026-09-18 21:52:47.537039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24e7f173a524'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add updated_at and is_deleted with defaults first, then make NOT NULL
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    
    # Set defaults for existing rows
    op.execute("UPDATE tickets SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("UPDATE tickets SET is_deleted = false WHERE is_deleted IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('tickets', 'updated_at', nullable=False)
    op.alter_column('tickets', 'is_deleted', nullable=False)
    
    op.alter_column('tickets', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tickets', 'ai_processed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tickets', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # Indexes already created in 0001_initial_schema:
    # ix_tickets_assigned_to, ix_tickets_category, ix_tickets_created_at,
    # ix_tickets_created_by, ix_tickets_priority, ix_tickets_status
    op.create_index('ix_tickets_assigned_status', 'tickets', ['assigned_to', 'status'], unique=False)
    op.create_index('ix_tickets_created_status', 'tickets', ['created_by', 'status'], unique=False)
    op.create_index('ix_tickets_deleted_created', 'tickets', ['is_deleted', 'created_at'], unique=False)
    op.create_index(op.f('ix_tickets_is_deleted'), 'tickets', ['is_deleted'], unique=False)
    op.create_index('ix_tickets_status_priority', 'tickets', ['status', 'priority'], unique=False)
    
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    
    # Set defaults for existing rows
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("UPDATE users SET is_deleted = false WHERE is_deleted IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('users', 'updated_at', nullable=False)
    op.alter_column('users', 'is_deleted', nullable=False)
    
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_at')
    op.drop_index('ix_tickets_status_priority', table_name='tickets')
    # ix_tickets_status and ix_tickets_priority dropped in 0001_initial_schema downgrade
    op.drop_index(op.f('ix_tickets_is_deleted'), table_name='tickets')
    op.drop_index('ix_tickets_deleted_created', table_name='tickets')
    op.drop_index('ix_tickets_created_status', table_name='tickets')
    # ix_tickets_created_by, ix_tickets_created_at, ix_tickets_category, ix_tickets_assigned_to dropped in 0001_initial_schema downgrade
    op.drop_index('ix_tickets_assigned_status', table_name='tickets')
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tickets', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'ai_processed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tickets', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('tickets', 'is_deleted')
    op.drop_column('tickets', 'updated_at')
    # ### end Alembic commands ###
