"""add ticket comments, history, and attachments models

Revision ID: 25a0cea01403
Revises: a7a64b882b8a
Create Date: 2026-09-19 13:15:57.496981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a0cea01403'
down_revision: Union[str, Sequence[str], None] = 'a7a64b882b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_attachments_created_at'), 'ticket_attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_is_deleted'), 'ticket_attachments', ['is_deleted'], unique=False)
    op.create_index('ix_ticket_attachments_ticket_created', 'ticket_attachments', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_uploaded_by'), 'ticket_attachments', ['uploaded_by'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_comments_author_created', 'ticket_comments', ['author_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_comments_author_id'), 'ticket_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_created_at'), 'ticket_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_comments_is_deleted'), 'ticket_comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ticket_comments_is_internal'), 'ticket_comments', ['is_internal'], unique=False)
    op.create_index('ix_ticket_comments_ticket_created', 'ticket_comments', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_index('ix_ticket_comments_ticket_internal', 'ticket_comments', ['ticket_id', 'is_internal'], unique=False)
    op.create_table('ticket_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TICKET_CREATED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ASSIGNED', 'UNASSIGNED', 'CATEGORY_CHANGED', 'SUBCATEGORY_CHANGED', 'TITLE_CHANGED', 'DESCRIPTION_CHANGED', 'COMMENT_ADDED', 'INTERNAL_NOTE_ADDED', 'ATTACHMENT_ADDED', 'ATTACHMENT_REMOVED', 'TICKET_REOPENED', 'TICKET_RESOLVED', 'TICKET_CLOSED', 'TICKET_REOPENED_AFTER_CLOSURE', 'PRIORITY_REASON_CHANGED', 'ASSIGNMENT_REASON_CHANGED', name='historyeventtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_history_actor_created', 'ticket_history', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_history_actor_id'), 'ticket_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_ticket_history_created_at'), 'ticket_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_history_event_type'), 'ticket_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_ticket_history_id'), 'ticket_history', ['id'], unique=False)
    op.create_index('ix_ticket_history_ticket_created', 'ticket_history', ['ticket_id', 'created_at'], unique=False)
    op.create_index('ix_ticket_history_ticket_event', 'ticket_history', ['ticket_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_ticket_history_ticket_id'), 'ticket_history', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_history_ticket_id'), table_name='ticket_history')
    op.drop_index('ix_ticket_history_ticket_event', table_name='ticket_history')
    op.drop_index('ix_ticket_history_ticket_created', table_name='ticket_history')
    op.drop_index(op.f('ix_ticket_history_id'), table_name='ticket_history')
    op.drop_index(op.f('ix_ticket_history_event_type'), table_name='ticket_history')
    op.drop_index(op.f('ix_ticket_history_created_at'), table_name='ticket_history')
    op.drop_index(op.f('ix_ticket_history_actor_id'), table_name='ticket_history')
    op.drop_index('ix_ticket_history_actor_created', table_name='ticket_history')
    op.drop_table('ticket_history')
    op.drop_index('ix_ticket_comments_ticket_internal', table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_index('ix_ticket_comments_ticket_created', table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_is_internal'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_is_deleted'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_created_at'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_author_id'), table_name='ticket_comments')
    op.drop_index('ix_ticket_comments_author_created', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_ticket_attachments_uploaded_by'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_ticket_id'), table_name='ticket_attachments')
    op.drop_index('ix_ticket_attachments_ticket_created', table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_is_deleted'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_id'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_created_at'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    # ### end Alembic commands ###
