"""add knowledge chunks and vector search

Revision ID: f905735f17e9
Revises: feddca4618fa
Create Date: 2026-10-08 01:45:40.993862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f905735f17e9'
down_revision: Union[str, Sequence[str], None] = 'feddca4618fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),  # Fallback for compatibility
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_article_id'), 'knowledge_chunks', ['article_id'], unique=False)
    op.create_index('ix_knowledge_chunks_article_idx', 'knowledge_chunks', ['article_id', 'chunk_index'], unique=False)
    op.create_index('ix_knowledge_chunks_created', 'knowledge_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_id'), 'knowledge_chunks', ['id'], unique=False)

    # Add vector column using pgvector type
    op.execute('ALTER TABLE knowledge_chunks ADD COLUMN embedding_vector vector(768)')

    # Create vector similarity index (HNSW for better performance)
    op.execute('CREATE INDEX IF NOT EXISTS ix_knowledge_chunks_embedding_hnsw ON knowledge_chunks USING hnsw (embedding_vector vector_cosine_ops) WITH (m = 16, ef_construction = 64)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_knowledge_chunks_embedding_hnsw')
    op.execute('ALTER TABLE knowledge_chunks DROP COLUMN IF EXISTS embedding_vector')
    op.drop_index(op.f('ix_knowledge_chunks_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_created', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_article_idx', table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_article_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###