"""add knowledge base models

Revision ID: feddca4618fa
Revises: phase2d3b_escalation_models
Create Date: 2026-10-07 22:26:32.481754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feddca4618fa'
down_revision: Union[str, Sequence[str], None] = 'phase2d3b_escalation_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'SECURITY', 'ACCOUNT', 'TROUBLESHOOTING', 'PROCEDURES', 'OTHER', name='article_category_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='article_status_enum', native_enum=False), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_author_id'), 'knowledge_articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_category'), 'knowledge_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_created_at'), 'knowledge_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_is_deleted'), 'knowledge_articles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_published_at'), 'knowledge_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_slug'), 'knowledge_articles', ['slug'], unique=True)
    op.create_index(op.f('ix_knowledge_articles_status'), 'knowledge_articles', ['status'], unique=False)
    op.create_index('ix_knowledge_deleted_created', 'knowledge_articles', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_knowledge_published_created', 'knowledge_articles', ['status', 'published_at'], unique=False)
    op.create_index('ix_knowledge_status_category', 'knowledge_articles', ['status', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_status_category', table_name='knowledge_articles')
    op.drop_index('ix_knowledge_published_created', table_name='knowledge_articles')
    op.drop_index('ix_knowledge_deleted_created', table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_status'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_slug'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_published_at'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_is_deleted'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_created_at'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_author_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    # ### end Alembic commands ###
